#!/usr/bin/env bash
# Refuse agent-pack commits that would reintroduce AI co-author trailers.
# Usage (sync / manual):
#   ./scripts/check-commit-msg.sh <<'EOF'
#   your message
#   EOF
# Or: git log -1 --format=%B | ./scripts/check-commit-msg.sh
set -euo pipefail
msg="$(cat)"
if printf '%s' "$msg" | grep -Eiq 'Co-Authored-By:|Co-authored-by:|Generated with|Generated by|🤖|cursoragent@cursor\.com|noreply@anthropic\.com'; then
  echo "REFUSE: agent-pack commit messages must not include AI/agent trailers or authorship." >&2
  echo "Strip Co-authored-by / Generated-with and recommit as rustafied only." >&2
  exit 1
fi
exit 0
