#!/usr/bin/env bash
# Refuse to push ANY commit whose message carries an AI/agent authorship trailer.
#
# Why this exists on top of the commit-msg hook: commit-msg only fires on a local
# `git commit`. Commits created another way — mirrored/copied from the field-guide
# website repo (where Co-authored-by is allowed), cherry-picked, rebased, made in a
# fresh clone without the hook, or committed with --no-verify — can still slip an
# AI trailer into agent-kit history and reintroduce `claude`/`cursoragent` on the
# GitHub Contributors list. This scans the full outgoing range on every push.
#
# Installed as .git/hooks/pre-push via scripts/install-hooks.sh.
# stdin lines: <local ref> <local sha> <remote ref> <remote sha>
set -euo pipefail

pattern='Co-Authored-By:|Co-authored-by:|Generated with|Generated by|🤖|cursoragent@cursor\.com|noreply@anthropic\.com'
zero='0000000000000000000000000000000000000000'
bad=0

while read -r local_ref local_sha remote_ref remote_sha; do
  [ "$local_sha" = "$zero" ] && continue   # branch deletion
  if [ "$remote_sha" = "$zero" ]; then
    range="$local_sha"                      # new branch: all reachable commits
  else
    range="$remote_sha..$local_sha"
  fi
  while read -r sha; do
    [ -z "$sha" ] && continue
    if git log -1 --format='%B' "$sha" | grep -Eiq "$pattern"; then
      echo "REFUSE (pre-push): $sha carries an AI/agent authorship trailer." >&2
      git log -1 --format='  %h %s' "$sha" >&2
      bad=1
    fi
  done < <(git rev-list "$range")
done

if [ "$bad" -ne 0 ]; then
  echo "" >&2
  echo "agent-kit history must stay rustafied-only. Strip the trailer (git rebase" >&2
  echo "or filter-branch --msg-filter) and re-push. See scripts/check-commit-msg.sh." >&2
  exit 1
fi
exit 0
